main: me.dio.arena.Arena
name: Arena
version: '1.0'
description: Arena PvP
author: dio-source
commands:
  archer:
    description: archer kit
    usage: /<command>
  vanilla:
    description: vanilla kit
    usage: /<command>